### ISSUE TITLE
可以提供一个菜谱名称的接口嘛。。。

### ISSUE THREAD

**Issue by 9527lhf** [Anduin2017/HowToCook#1007]
前台调用接口生成随机的菜品，再也不用纠结今天吃啥了

**Comment by Anduin2017** [comment]
需要先clone下来，然后再用自己喜欢的文件系统API来获取。

示例：

https://github.com/Anduin2017/HowToCook/blob/b5a4e21dd0be5d2f887bb4ceb3cf45fb0130a832/.github/readme-generate.js#L81-L89
