### ISSUE TITLE
大家觉得蛋炒饭是先放饭好还是先放蛋好？

### ISSUE THREAD

**Issue by rese1f** [Anduin2017/HowToCook#1027]

**Comment by Mars1egend** [comment]
把鸡蛋分成蛋黄和蛋清
蛋黄拌饭做准备
蛋清下油锅炒到半熟下米饭
大概5分钟翻炒之后放葱花和盐调味出锅

**Comment by Reself-C** [comment]
> 

谢谢你，这对蓝狗留学生真的很重要。

**Comment by Zhoushunshun541** [comment]
> 把鸡蛋分成蛋黄和蛋清 蛋黄拌饭做准备 蛋清下油锅炒到半熟下米饭 大概5分钟翻炒之后放葱花和盐调味出锅

实际上，我不太喜欢这种口感，我喜欢颗粒分明的那种蛋炒饭，直接冷油放蛋，一直搅，搞碎点，然后放菜放饭炒，米饭也要放置一阵子，免得太黏了

**Comment by HuWenjin** [comment]
蛋炒饭有很多种,一般能做出一粒一粒的就是用过夜的饭,加一点生粉抓散,然后根据量加入蛋黄一个或多个,然后再抓匀.注意用手套.
蛋黄的多少和是否拌匀决定了最后的黄金蛋炒饭的黄金成色.
锅里加点油,小火,把葱放进去炒一会儿,同时把油润锅.出来葱香味后把米饭放进去,注意是中小火,不停的翻炒,要不停,要不然可能粘锅.
炒上5到10分钟,看见米变成一粒粒金黄色就行了.关小火,再把蛋清直接倒到米上面(要注意整个过程中蛋是没有打散的.)然后开大火,要更快速的翻炒米饭直到看见蛋清变白色,就关小火.金银蛋炒饭基本好了.
1: 加点生抽翻炒均匀,(喜欢焦的,可以再开大火炒焦一点)
2: 加盐,味精,胡椒,青豆,香肠粒翻炒均匀,得到扬州炒饭
3: 加点卤汁,洋葱粒,放些叉烧和青菜在上面,得到黯然销魂饭
4: 加酸豆角肉末...
5: 加你喜欢的其它配菜.

这样炒出来费饭,一般吃二两的可能不知不觉四两都没有了,还觉得没吃一样,可以比平时多做一些.

**Comment by rain78** [comment]
米饭冷藏一夜，第二天炒之前打一个鸡蛋在米饭上，搅拌，让每粒米都裹上蛋液，完了用油炒差不多放在鸡喜欢的蔬菜（切成鼎鼎或者丝状最好） 出锅撒葱花 ，完美！
