### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Trahaswi** [Anduin2017/HowToCook#1031]
Can someone translate this to english. OMG it looks like a lot different to me.

**Comment by HuWenjin** [comment]
Click the mouse right button, and choose to translate to english.

**Comment by Anduin2017** [comment]
For non-Chinese, the crafting techniques and styles in this recipe may not be easily acceptable. Of course, if you're using it for Chinese food practice, I think you can use Google Translate.

However, think about it the other way around: when you have started practicing Chinese food, you should also learn some Chinese knowledge.

**Comment by aholten** [comment]
对于这个英文翻译的项目我有兴趣。 虽然我的翻译速度挺慢的， 但是关于普通话和中式做饭，这样相关的话题等，我的经应该足够的。

I'm interested in providing an English localization-- I am not a very fast translator but as a home cook who is knowledgeable on Mandarin and Chinese cuisine I think I could do a decent job.
