### ISSUE TITLE
拔丝土豆需要500ml油吗？

### ISSUE THREAD

**Issue by Clown666** [Anduin2017/HowToCook#1039]

**Comment by Anduin2017** [comment]
At 原作者 @draem0507

**Comment by jcq-1129** [comment]
炸土豆的量因人而异吧 而且还得看你土豆的数量

**Comment by NiuYaQ** [comment]
没事 炸完的油可以买个油壶放起来

**Comment by Anduin2017** [comment]
实际做了一次，感觉确实不需要500ml。但是搜索了大量网上的资料，往往只提及需要“大量”食用油。没人知道到底需要多少量。这里暂时标注300ml。如果有更清晰的标准再补充。

**Comment by leetshow** [comment]
有几个因素会影响到油的使用量
1. 平底锅还是圆形锅 2. 土豆量 3. 吐口切的大小
我当时是2个土豆，300g 左右 ，实际使用流量再 350~500 之间（时间久有点忘记了）
一般经验是土豆能浮在油上面即可
