### ISSUE TITLE
辅料技巧的WHO减盐相关链接问题

### ISSUE THREAD

**Issue by Y-Z-Chen** [Anduin2017/HowToCook#1043]
辅料技巧一栏的WHO链接应当修改为https://www.who.int/zh/news-room/fact-sheets/detail/salt-reduction （原文给出的链接https://www.who.int/news-room/fact-sheets/detail/salt-reduction 是英文版，本菜单使用中文，应保持一致）

**Comment by Anduin2017** [comment]
PR Welcome!
