### ISSUE TITLE
也许能设计一种领域特定语言，适于描述标准化的烹饪流程？

### ISSUE THREAD

**Issue by rn7s2** [Anduin2017/HowToCook#105]
也许能设计一种领域特定语言，适于描述标准化的烹饪流程？
有一些希望教程量化、更精确的Issue，也许我们能够利用这个repo的信息，归纳出合理好用的标准流程，并将其设计成语言。
输入各种食材，经过程序变换，输出成品菜肴。
😄，当然只是拍个脑门，说不定能实现会编程就会做菜哈

**Comment by recolic** [comment]
#60

**Comment by Anduin2017** [comment]
Duplicate #60
