### ISSUE TITLE
关于长岛冰茶可乐用量的问题

### ISSUE THREAD

**Issue by eitchhh** [Anduin2017/HowToCook#1072]
关于可乐的用量，计算栏和操作栏显示的不一致。
一杯的用量是75ml还是20ml？

**Comment by Anduin2017** [comment]
根据引用：https://www.xiachufang.com/recipe/1072625/ 和 https://iba-world.com/long-island-ice-tea/  要想装满图中大约300ml的杯子的上四分之一，确实需要约 75ml 的可乐。
