### ISSUE TITLE
建议对菜品进行分类

### ISSUE THREAD

**Issue by Zhang-RQ** [Anduin2017/HowToCook#109]
建议对菜品进行分类，比如按菜系或其它分类标准。
这样可以提高目录的整洁度和repo的结构性。

**Comment by Anduin2017** [comment]
PR welcome

**Comment by Anduin2017** [comment]
已经按文件用途重构

**Comment by recolic** [comment]
如果用户需要用多种分类标准进行分类（例如菜系、口味、难度），我们可能需要一种更好的方案，来维护这些分类。

**Comment by Anduin2017** [comment]
我认为可以重定向这个issue到 #3
