### ISSUE TITLE
Is there a way to export to pdf?

### ISSUE THREAD

**Issue by RedemptionC** [Anduin2017/HowToCook#1142]
I installed all the dependency and run `mkdocs build --clean`
failed with this error:
>OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by HernandoR** [comment]
Mark with [deploy-pdf](https://github.com/kartoza/mkdocs-deploy-build-pdf) and [actions](https://github.com/marketplace/actions/deploy-mkdocs)

**Comment by Anduin2017** [comment]
I will consider adding this task and provide official PDF releases.

**Comment by Anduin2017** [comment]
I added a PDF plugin. Now PDF is supported.

However, there seems to be some issue with the plugin that the generated PDF file only contains half of the dishes. (Only 193 pages)

Investigation still needed.
