### ISSUE TITLE
能不能和novelai联动一下

### ISSUE THREAD

**Issue by EnderAvaritia** [Anduin2017/HowToCook#1148]
我是说这个

![1666425593543.jpeg](https://user-images.githubusercontent.com/84321282/197327982-857ab305-4ed1-45b4-b522-829e59e0c9de.jpeg)

**Comment by Yang-qwq** [comment]
作者应该不会做和novelai相关的东西，你或许可以自己训练？

**Comment by Anduin2017** [comment]
Ref: https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md

你可以自己训练。
