### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by duanyaozong** [Anduin2017/HowToCook#1170]
去腥篇蘸料里应为芝麻酱，而不是将

**Comment by pa733** [comment]
建议像 #1100 一样交个pr，方便你我他。

**Comment by Anduin2017** [comment]
PR Welcome

**Comment by ArtieLiu** [comment]
This typo has been fixed by [this](https://github.com/Anduin2017/HowToCook/pull/1173) pr, and this issue can be closed.

**Comment by Anduin2017** [comment]
Thanks @ArtieLiu !
