### ISSUE TITLE
能不能更新钻木取火的教程

### ISSUE THREAD

**Issue by LYH-YF** [Anduin2017/HowToCook#1191]
天然气停气的情况下不work

**Comment by cubxxw** [comment]
可以的亲，请问您用 **法拉利药匙** 钻木还是用 **劳斯莱斯雨伞** 取火？

**Comment by pisces365** [comment]
钻木取火其实很简单，先这样，在那样，就好啦

**Comment by Erebus-qie** [comment]
> **材料准备：**比较干燥的地点，易燃的火引子（多份）（也作火绒）（比如干燥，枯黄的草），一根直木棒（最好无枝干，相对来说比较光滑，否则对你的手不太友好），一块木板（干燥，中间最好有凹陷，可以放火引子），一些干柴（如果没有，请寻找附近的树（或者木本植物），并取下它的枝干，晾晒若干天（视当地情况而定））#干柴的代用品可以为干燥的草本植物，但燃烧的持续时间会缩短，请视情况而定.

> **下面是做法：**
1. 首先要一个火引子，聚在一起，可以做成鸟巢一样，也可以是圆形。
2. 再有一根合适的木棒，还要一小块木板，上面钻一个洞，开一个槽。
3. 用脚踩紧木板，或者以别的方式不让它随意移动。
4. 将火引子放到木板凹陷处，状态为蓬松（确保空气流通）
5. 拿起木棒对准凹陷处，用双手来回搓动手上的木棒，使木板的小洞开始冒烟。
6. 继续搓动，当磨擦的热量足够多的时候，磨出来的精细粉末会被点着。
7. 小心地把火引子拿起来（上一步输出的是火星，很容易熄灭），（先咽一口吐沫，防止口中水分使火星熄灭）轻轻地往里边吹起，这时会看到通红的火星（并极大可能伴有轻微燃烧）#注意：这一步可能生成烟雾以及一氧化碳，请注意人身安全。
8. 把火引子放地上，再加一份火引子使其燃烧的更剧烈，之后点燃干柴，并使干柴成三角锥形或发散状的星形（※），就会拥有一堆火。

**Comment by Anduin2017** [comment]
PR Welcome
