### ISSUE TITLE
黄瓜炒肉只炒半分钟黄瓜能熟吗

### ISSUE THREAD

**Issue by Hlongyu** [Anduin2017/HowToCook#1210]
https://github.com/Anduin2017/HowToCook/blob/master/dishes/meat_dish/%E9%BB%84%E7%93%9C%E7%82%92%E8%82%89.md
今天试了一下，半分钟远远不够啊。难道你们黄瓜炒肉吃的生黄瓜吗

**Comment by xihuanyigeren123** [comment]
可能每个人家里的火力不一样，你不能按照教程严格的时间。

**Comment by RaysLinn** [comment]
按照文档里的说法切成0.5cm薄片的话，用火灶（天然气/煤气/柴火）开中火到大火炒30秒肯定是[断生](https://zh.wikipedia.org/zh-hans/%E6%96%AD%E7%94%9F)了的。

如果家里用的是[电磁炉](https://zh.wikipedia.org/zh-hans/%E9%9B%BB%E7%A3%81%E7%88%90)，则可能时间略长。本人测试过50秒到60秒。

黄瓜断生的标志个人认为应该是黄瓜片开始变透明，至于透明的程度就是自己把握的了。

个人经验，仅供参考

**Comment by lzh1104** [comment]
这个没注明火力。是个**bug**
