### ISSUE TITLE
希望能增加自定义菜品功能

### ISSUE THREAD

**Issue by ailler-cc** [Anduin2017/HowToCook#1217]
有些菜在家人的指导下完成了，并且味道还算不错。但是一段时间不做以后总是容易遗忘，希望能自定义菜品，将一些官方菜谱上没有的菜品进行记录，方便后续自行查阅，或者也能将自定义的菜品分享出来

**Comment by Anduin2017** [comment]
https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md
