### ISSUE TITLE
菜品的菜谱多版本支持

### ISSUE THREAD

**Issue by RockChinQ** [Anduin2017/HowToCook#124]
如果有人想对现有菜谱的菜品提交自己的菜谱，可否在README.md里面引导一下如何添加以及添加的格式？

**Comment by Anduin2017** [comment]
## 如何贡献

直接修改\添加做菜指南并提交 Pull request 即可。

在写新菜谱时，请复制并修改已有的模板: [示例菜](https://github.com/Anduin2017/HowToCook/blob/master/dishes/template/%E7%A4%BA%E4%BE%8B%E8%8F%9C/%E7%A4%BA%E4%BE%8B%E8%8F%9C.md)。

记得在提交 Pull Request 前同样更新一下 Readme.md 里的引用。

**Comment by RockChinQ** [comment]
我的意思是，若一种菜品有多个人提交了不同的菜谱，应该如何区分

**Comment by Anduin2017** [comment]
> 我的意思是，若一种菜品有多个人提交了不同的菜谱，应该如何区分

不允许重复。如果一个菜已经被收录了，那么其它人将只能编辑它，提供更多信息或优化流程。或提交一个全新的完全不同的做法、风味。不能收录两次同名菜。
