### ISSUE TITLE
无所谓用量的材料怎么标注

### ISSUE THREAD

**Issue by ch1lam** [Anduin2017/HowToCook#127]
比如说姜片，主要作用就是去腥，切片的大小，数量都无所谓的，这应该怎么标注呀？

**Comment by recolic** [comment]
建议标注一个自己认为可以接受的量, 作为一个example而不是一个完美的标准. 例如:

这个姜片切多切少都可以, 但我觉得5片就是一个不错的例子. (其实10片也可以) 就可以标注为: 姜切薄片约5片.

**Comment by Anduin2017** [comment]
> 建议标注一个自己认为可以接受的量, 作为一个example而不是一个完美的标准. 例如:
> 
> 这个姜片切多切少都可以, 但我觉得5片就是一个不错的例子. (其实10片也可以) 就可以标注为: 姜切薄片约5片.
> 
> 或者可以给定一个大致的范围, 例如5g-20g都可以. 这样子

可以加入`模板`中和`贡献指南`中。

**Comment by i-guyue** [comment]
适量

**Comment by Anduin2017** [comment]
> 适量

这个仓库中不允许出现 `适量` 这个词。
