### ISSUE TITLE
个人觉得这个做菜教程不是很实用

### ISSUE THREAD

**Issue by RunningV** [Anduin2017/HowToCook#1288]
网上有各种教做菜的视频，看视频学习炒菜比这种文字更容易理解；同一种菜不同厨师有各种炒法，做出的味道也各有喜好。
我也经常在家做饭，经常会将同一道菜的不同视频做法看一看，然后自己学习做，比这种单一的文字描述更直观易上手。
我认为作者这个做菜教程并没有很多实际用途，只能提供大概的做菜方法，所以我提两点建议：
1. 将菜谱表格化，特别是分量、油盐的多少要表述清楚；
2. 应该将每个菜的步骤格式化，可以发展成为一个做菜语料库，为以后的炒菜机器人提供语料才是好的方向。

**Comment by Anduin2017** [comment]
现在不是已经把分量和多少都表述清楚了么

**Comment by Nukami** [comment]
同意，我现在是跟着文档，自己再整理一遍执行脚本，然后才开工，要是能更规范一些就方便多了

**Comment by 2021fuck** [comment]
这教程也就一乐子，我随便点了一个回锅肉，他居然是生肉直接炒。。。。。

**Comment by Anduin2017** [comment]
> 这教程也就一乐子，我随便点了一个回锅肉，他居然是生肉直接炒。。。。。

At 回锅肉原作者： @fissssssh

**Comment by fissssssh** [comment]
> 这教程也就一乐子，我随便点了一个回锅肉，他居然是生肉直接炒。。。。。

五花肉一段处理不看的？

**Comment by fissssssh** [comment]
> > 这教程也就一乐子，我随便点了一个回锅肉，他居然是生肉直接炒。。。。。
> 
> 五花肉一段处理不看的？呆逼！

不知道谁给弄了不是回锅肉的PR在回锅肉里面。。。。。
