### ISSUE TITLE
不是，哥们儿，真是做饭的教程啊

### ISSUE THREAD

**Issue by s1mpleocode** [Anduin2017/HowToCook#1315]
真不错，很实用，哪个程序员不喜欢程序得来的成果呢
![118088715_105416034620130_4699932976446482046_n](https://github.com/Anduin2017/HowToCook/assets/103562905/aab68521-853c-4f14-aa59-e5d240a5afa8)

**Comment by dengmuzhi123** [comment]
发给我爸看，让他照着里面的做
