### ISSUE TITLE
关于完善单元测试的建议

### ISSUE THREAD

**Issue by 520MianXiangDuiXiang520** [Anduin2017/HowToCook#132]
为了提高项目质量，避免有黑暗料理被恶意加入代码库，建议新增 test 目录，并保持和菜单项同步更新，大家做好后可以上传烹饪结果供后来者参考。

**Comment by hwangdeyu** [comment]
顺路增加个网友实践经验和效果展示图？lol

**Comment by hax** [comment]
测试用例怎么写？

**Comment by Ges0ng** [comment]
黑暗料理可还行

**Comment by MagicHacker** [comment]
如何判断是黑暗料理？

**Comment by Ges0ng** [comment]
> 如何判断是黑暗料理？

QA一遍就知道了

**Comment by Anduin2017** [comment]
如果你们吃到了黑暗料理，可以来issue里吐槽。

**Comment by xwnb** [comment]
哈哈哈哈，我加了个测试文件夹，欢迎大家一起来 review：https://github.com/Anduin2017/HowToCook/pull/341
