### ISSUE TITLE
Readme的列表

### ISSUE THREAD

**Issue by yray680** [Anduin2017/HowToCook#1326]
能不能往后排版，很少人有耐心一直下拉，列表多放点A标签呗。纯个人建议。

**Comment by Anduin2017** [comment]
没看懂这个需求。请清晰准确的描述一下问题是什么

**Comment by yray680** [comment]
> 没看懂这个需求。请清晰准确的描述一下问题是什么

个人感觉下拉菜单太长了，一行就3-4个字，好浪费空间的。
纯个人喜好，不喜勿喷。

**Comment by Anduin2017** [comment]
![image](https://github.com/Anduin2017/HowToCook/assets/19531547/ed533da5-c627-43b3-8774-2acf19e2697e)

请使用 Docker 版本。Readme 文件本身只是归档使用，以最终编译出来的 Web Portal 为准。
