### ISSUE TITLE
🍽 感觉按照流程做也有难度，有没有按照菜系推荐餐馆啊

### ISSUE THREAD

**Issue by guokaigdg** [Anduin2017/HowToCook#1344]
先想到吃什么菜，然后进去看看到响应的餐馆，可以按地区分，能外卖的那当然是最好啦，适合懒人。
 🌰：小炒肉点击去 -> 然后推荐费大厨 -> 然后正好有外卖

**Comment by Anduin2017** [comment]
![image](https://github.com/Anduin2017/HowToCook/assets/19531547/b8b7f018-1ae0-4f7a-9cfd-5391b6500b5a)
