### ISSUE TITLE
程序员哪有时间做饭，求泡面好吃的做法

### ISSUE THREAD

**Issue by ycrxun** [Anduin2017/HowToCook#1346]

**Comment by gitchong** [comment]
冷水泡面最好吃。

**Comment by Anduin2017** [comment]
https://github.com/Anduin2017/HowToCook/blob/master/dishes/staple/%E7%82%92%E6%96%B9%E4%BE%BF%E9%9D%A2.md

炒方便面。有泡面有锅有水有油就能做。花的时间没比泡面增加多少，却好吃了一大截。
