### ISSUE TITLE
除去docker，我该如何在编译器里启动该项目

### ISSUE THREAD

**Issue by 1138306694** [Anduin2017/HowToCook#1357]
git clone后 我该如何在本地启动一个的页面来访问查看。
package.json 的scripts中 似乎没有。
我不想通过docker的方式下载镜像，仅仅想在本地环境看。
不知道有什么方式吗？

**Comment by Anduin2017** [comment]
这是一个标准的 mkdocs 项目。按照mkdocs的启动方法即可：

```bash
pip install -r requirements.txt
mkdocs build
```

这会生成一个文件夹，其中皆为静态文件。

**Comment by guou123** [comment]
’mkdocs build‘运行过后：
出现‘Error: Config file 'mkdocs.yml' does not exist.’
