### ISSUE TITLE
速冻混沌做法需要修改

### ISSUE THREAD

**Issue by Zawinzala** [Anduin2017/HowToCook#1369]
几乎不可参考，一看就不行。

**Comment by Zawinzala** [comment]
> 将水倒入电饭煲中，按炖或煮的模式运行 35 分钟，此时揭开电饭煲应看到水为沸腾状态。

首先就是这个35分钟也太主观了，而且什么电饭煲煮水要35分钟啊。不同功率的电饭煲都不一样。

> 盖上电饭煲，按同样炖或煮的模式运行 20 分钟。

同理，这个时间如果功率大直接烂了吧。

相比另一个菜谱，煮饺子那个，这个煮混沌完全不行。

**Comment by Anduin2017** [comment]
AT 原作者 @Maples7

**Comment by Maples7** [comment]
我按这个方式实践过多次，每次都没问题。在「必备原料和工具」里面已经注明推荐智能电饭煲，都自带温控和智能功率调节，根本没用功率选项。

你说有问题你实践过后自己改吧 @Zawinzala 。

**Comment by Zawinzala** [comment]
不同功率的电饭煲都不一样啊，我的电饭煲10分钟就能烧开水，那按照这个菜谱，先是干烧20分钟的水，然后把馄饨煮烂。
你说的智能电饭煲也是。。不太合理的描述。。不同电饭煲的策略都不一样。差别极大。你大可以把自己电饭煲的型号写在上面。不然就和用智能手机苹果4g，举例智能手机如何打开原神一样离谱吧。
我不知道你电饭煲是什么牌子，功率，策略。不同电饭煲差别很大。不是一句只能电饭煲就能囊括的吧。
这和这个项目的精密初衷不一。

**Comment by Maples7** [comment]
1. 食谱[已注明推荐电饭煲品牌](https://github.com/Anduin2017/HowToCook/blob/master/dishes/semi-finished/速冻馄饨.md#必备原料和工具)，不注明型号是避免植入嫌疑。而且我相信目前市面上的小米智能电饭煲都适用于该食谱，因为这个食谱的原始版本出自米家 App 的电饭煲食谱推荐。
2. 你的电饭煲不是智能电饭煲，代表**很有可能**该食谱**不适用于你的设备**，**请勿简单机械参考**。
3. 你的电饭煲虽然不是智能电饭煲，在水量明确清晰且足够的情况下，不代表 10 分钟能煮开的水煮 35 分钟不能达到同样的效果。
4. 你觉得这个食谱不适用于你，请自行贡献出适用于你的「非智能电饭煲」的「速冻馄饨」版本并注明设备。该食谱完美准确适用于我的设备，我不可能用我的设备写出适用于你的设备的满意食谱，更不可能也没义务写出能适用于穷举市面上所有电饭煲的「速冻馄饨」「电饭煲做法」的版本。你觉得有问题那你自己提 PR 改，就这么简单。

@Zawinzala

**Comment by Zawinzala** [comment]
ok，谢谢回复。不过电饭煲这个我就不掺和了，后面遇到煮馄饨的时候看情况补一个水煮版本hh。
我的也是小米的电饭堡。不过它的步骤和你不一样哦。上面写着沸腾后加。而不是半小时。35分钟米饭都熟啦。
本消息不用回复。我自行关闭
