### ISSUE TITLE
200g是多少，半瓶盖吗，怡宝瓶盖，15ml是多少

### ISSUE THREAD

**Issue by hcieget110** [Anduin2017/HowToCook#1377]
200g是多少，半瓶盖吗，怡宝瓶盖，15ml是多少

**Comment by Karben233** [comment]
一罐可乐是330毫升，所以是三分之二罐可乐那么多

**Comment by khgkhg** [comment]
> 200g是多少，半瓶盖吗，怡宝瓶盖，15ml是多少

简单方便算 15ml 直接等价为 15g。200g其实就是4两重。200/15 = 13.3瓶盖
