### ISSUE TITLE
请问为什么在dockerhub中无法搜索到这个项目，也无法部署？

### ISSUE THREAD

**Issue by immoke** [Anduin2017/HowToCook#1381]
![image](https://github.com/user-attachments/assets/0d8277ff-f481-4a96-80c9-05b1c5d7b5f5)

**Comment by Anduin2017** [comment]
这个项目就没有发布到 Docker 自己运营的 DockerHub 上。相反，它发布到的是 GitHub 运营的 DockerHub 上。

如果你需要拉取这个项目，请拉取 image：`ghcr.io/anduin2017/how-to-cook:latest`
