### ISSUE TITLE
炒年糕未注明盐的具体用量

### ISSUE THREAD

**Issue by yinghuo-ex** [Anduin2017/HowToCook#1382]

**Comment by chenyuchenlijingshuo** [comment]
炒年糕时盐的用量会因个人口味、年糕的量以及其他配料的多少而有所不同，一般来说，每200 - 300克年糕可使用1 - 2克盐
影响盐用量的因素 ：1个人口味偏好，不同人对咸淡的喜好差异较大。如果喜欢口味清淡些，每200克年糕可使用1克左右盐；若口味偏重，每200克年糕可增加至1.5 - 2克盐。2年糕的量：炒年糕时，盐的用量应根据年糕的实际重量进行适当调整。如果年糕的量较多，相应地需要增加盐的用量，但并非成严格的正比关系。3其他配料的影响：炒年糕时通常会搭配其他食材，如蔬菜（白菜、胡萝卜等）、肉类（火腿、牛肉等）或酱料（甜辣酱、豆瓣酱等），这些配料的咸淡程度会影响盐的用量。如果使用了咸度较高的配料，如腌制过的火腿或豆瓣酱，应适当减少盐的添加量。以加入50克咸火腿为例，每200克年糕的盐用量可减少0.5 - 1克。
盐用量的一般范围 ：在没有特殊配料影响且口味适中的情况下，每200 - 300克年糕使用1 - 2克盐是一个较为常见的基础用量范围。这个用量可以使年糕在炒制过程中基本入味，同时不会过于咸口。调整原则：在实际烹饪过程中，应边炒制边尝味道，根据个人口味和其他因素进行灵活调整。如果在炒制过程中发现味道偏淡，可以适量添加少量盐进行调味；若感觉过咸，可以加入一些配菜（如土豆、年糕等）来吸收盐分，或者添加少量水和糖来缓解咸味。 炒年糕时盐的具体用量需综合考虑个人口味、年糕量以及其他配料等因素，通过不断尝试和调整，找到最适合自己的口味。同时，合理的盐用量不仅能提升炒年糕的口感，也有助于保持健康的饮食习惯。
