### ISSUE TITLE
手工水饺中的锅盖问题

### ISSUE THREAD

**Issue by AsenHu** [Anduin2017/HowToCook#1383]
https://github.com/Anduin2017/HowToCook/blob/c4078c8157a985365dfe238ab341e42c53bffda4/dishes/staple/%E6%89%8B%E5%B7%A5%E6%B0%B4%E9%A5%BA.md?plain=1#L71

要求揭开锅盖前并没有要求关上锅盖。

我自己煮的时候发现的，但就算没有关上锅盖，看上去也没有什么大问题。

我觉得或许可能可以移除揭开锅盖？（主要是这是我第一次做饭，感觉上来就改不太好）

**Comment by AsenHu** [comment]
我这几天再煮几次试试

**Comment by Anduin2017** [comment]
感觉是个错误。不过欢迎大佬试验后提出修正意见

**Comment by yuyun2000** [comment]
我煮饺子从不盖盖

**Comment by AnInteger** [comment]
煮水饺不需要盖锅盖，加三次水就是为了不让饺子一直处于沸腾状态导致表皮破损变成面片

**Comment by Anduin2017** [comment]
我觉得可以修改这个内容，建议读者不要盖盖。

**Comment by myworksfun** [comment]
![img_2024-12-02_15-07-13](https://github.com/user-attachments/assets/f2a9ed60-049d-4eb2-9cfc-a6fdb72fd60a)
**docker 版本预计何时再次更新？**😄

**Comment by Anduin2017** [comment]
Docker版本实时更新。请直接拉取 latest
