### ISSUE TITLE
关于计数单位的疑惑

### ISSUE THREAD

**Issue by Bravo123** [Anduin2017/HowToCook#150]
有没有可能大家（比如我🤭）对于克数并不是很了解。
是否考虑用更通俗易懂的方式比如一小勺，两小勺盐代替4g盐；2个土豆代替200g土豆；10滴左右代替5ml的油。

**Comment by gccio** [comment]
我认为每个人的“小勺“大小不同，无法成为统一的计量单位，还是克和毫升比较好。

**Comment by Anduin2017** [comment]
> 有没有可能大家（比如我🤭）对于克数并不是很了解。 是否考虑用更通俗易懂的方式比如一小勺，两小勺盐代替4g盐；2个土豆代替200g土豆；10滴左右代替5ml的油。

之前就是用几个描述西红柿。结果西红柿有大有小，有的人溢出了有的人不够吃

**Comment by Anduin2017** [comment]
Won't fix.
