### ISSUE TITLE
关于完善西红柿炒鸡蛋的做法的建议

### ISSUE THREAD

**Issue by SSadamune** [Anduin2017/HowToCook#162]
## 建议

建议增加”加葱花、不加糖“的做法。

番茄炒蛋作为一款全民级美食，加糖/不加糖是两大主要流派。
双方均有数量可观的拥趸，为提升做法的灵活性，满足不同的口味需求，
建议将是否放糖（以及是否添加葱花）修改为可选项。

## 参考
https://www.xiachufang.com/recipe/1012917/

> （1169赞）你这个菜谱没放白糖，给你五颗星！超烦番茄炒蛋放糖的
> （351赞）偷偷告诉大家，抄鸡蛋的时候稍微放一点点白糖，鸡蛋会比较嫩

**Comment by Anduin2017** [comment]
PR welcome

**Comment by kshen91** [comment]
很难不赞同

**Comment by xbj126** [comment]
请更新煮法：
1、热锅冷油，放鸡蛋5个，不打散，半凝固时翻面，70%熟时打散成大块。
2、鸡蛋不用乘出，直接放番茄丁，焖煮翻炒，重点：不加水。待锅太干时加零星一丁水，继续翻炒，番茄越煮越多水份，不用担心烧干。【important ：加了水就不好吃了】
3、不加糖、不加糖、不加糖
4、加适当盐、酱油、葱花

**Comment by zhaoyunxing92** [comment]
> 请更新煮法： 1、热锅冷油，放鸡蛋5个，不打散，半凝固时翻面，70%熟时打散成大块。 2、鸡蛋不用乘出，直接放番茄丁，焖煮翻炒，重点：不加水。待锅太干时加零星一丁水，继续翻炒，番茄越煮越多水份，不用担心烧干。【important ：加了水就不好吃了】 3、不加糖、不加糖、不加糖 4、加适当盐、酱油、葱花

70%熟很难估量吧，还有我喜欢放点生抽

**Comment by Anduin2017** [comment]
Reference #55

**Comment by recolic** [comment]
PR已经merge,请确认此issue是否已解决。
