### ISSUE TITLE
米饭不同品种的米，不同的水量会极度影响口感

### ISSUE THREAD

**Issue by Emily-0616** [Anduin2017/HowToCook#170]
南方一般食用江南米，北方一般食用北方大米，江南米会比较细长，而北方大米会比较短且圆。
米的不同，水量也不同，错误的水量会极度影响口感。
以下是我疫情居家隔离得出的结论，不论什么容器下：
江南米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截的一半。
北方大米，米和水放在同一容器内，食指触及米，水量没过食指的第一个指截。
[米](https://github.com/Anduin2017/HowToCook/blob/master/dishes/staple/%E7%B1%B3%E9%A5%AD.md)

**Comment by Anduin2017** [comment]
PR welcome.

**Comment by WakiJi** [comment]
坐标南方内陆城市，一般用的米即使加到第一指戳的一半仍会出现“米饭过稀”问题，我个人一般是水量加到超过米面 0.5 cm - 0.8 cm

**Comment by Emily-0616** [comment]
> 坐标南方内陆城市，一般用的米即使加到第一指戳的一半仍会出现“米饭过稀”问题，我个人一般是水量加到超过米面 0.5 cm - 0.8 cm

我的我的，应该是一半的一半....

**Comment by whsir** [comment]
锅不同，一样会影响口感

**Comment by Anduin2017** [comment]
Fixed by #173.
