### ISSUE TITLE
feat: 增加上下节文章联系 方便阅读时切换

### ISSUE THREAD

**Issue by Fjaxzhy** [Anduin2017/HowToCook#177]
还是有机会研究一下能够自动生成这个页脚的脚本

_Originally posted by @Anduin2017 in https://github.com/Anduin2017/HowToCook/issues/137#issuecomment-1046481536_

其实我觉得塞在模板里让作者自己加就行 (
顺序按README的顺序排就成

**Comment by Anduin2017** [comment]
太伤肝……

**Comment by Fjaxzhy** [comment]
> 太伤肝……

干脆直接塞进vuepress

**Comment by corle-bell** [comment]
有现成的模板啊。可以换过去就行 直接把md迁移过去就行

**Comment by Anduin2017** [comment]
已经开发完成了这个功能。

**Comment by Anduin2017** [comment]
https://cook.aiurs.co
