### ISSUE TITLE
关于`泡发时间过长的木耳`

### ISSUE THREAD

**Issue by ckvv** [Anduin2017/HowToCook#182]
和我合租一妹子，木耳泡了n天，水硬是蒸发完了又变成了干木耳，后来木耳不见了，估计她是吃了

**Comment by Anduin2017** [comment]
是说，需要在文档中提及不要把木耳泡太久吗

**Comment by ckvv** [comment]
@Anduin2017 文档上面有提及，我就是看到了才想起来
https://github.com/Anduin2017/HowToCook/blob/47b542ac52a3968a7f124a502ed081cbe7963633/tips/learn/%E9%A3%9F%E5%93%81%E5%AE%89%E5%85%A8.md?plain=1#L12
