### ISSUE TITLE
图片链接失效

### ISSUE THREAD

**Issue by TulipLi** [Anduin2017/HowToCook#200]
## 示例图片失效

<img width="684" alt="image" src="https://user-images.githubusercontent.com/24578248/154942827-f3cb8d1b-2423-43ae-ae04-4eb9ba9a6f37.png">
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/24578248/154942854-cf1207c3-dff2-4801-b75f-571fe9d5afc3.png">

**Comment by Anduin2017** [comment]
Duplicate #97.
