### ISSUE TITLE
建议：增加更详细的电子压力锅使用方法和菜谱

### ISSUE THREAD

**Issue by scaomath** [Anduin2017/HowToCook#217]
自己疫情之后因为老婆要带娃就给全家人做饭，为了节约时间常年使用instant pot，总结了

- 很多菜谱
- 口感据时间材料用量的分析
- 另：现在的高压锅使用方法是针对传统的单阀门物理压力锅，并不针对更为安全和方便的电子压力锅。

可以PR吗？

**Comment by Anduin2017** [comment]
PR welcome. PR时请参考模板。
