### ISSUE TITLE
糖醋里脊全写的是适量。。

### ISSUE THREAD

**Issue by co2color** [Anduin2017/HowToCook#228]

**Comment by Anduin2017** [comment]
@2096779623

Nice catch

十分感谢。这个确实是个非常严重的问题。我会马上push原作者来修改。

Hi，原作者 @2096779623

您好，感谢贡献！但是看起来它的内容格式和约束的标准差距很大。您先改改我再重新review。

参考：https://github.com/Anduin2017/HowToCook/blob/master/CONTRIBUTING.md

**Comment by Anduin2017** [comment]
Fixed by #246
