### ISSUE TITLE
煮饺子使用铲子而不是勺子。

### ISSUE THREAD

**Issue by ytc1012** [Anduin2017/HowToCook#229]
为啥要用铲子？勺子了解一下？

**Comment by Anduin2017** [comment]
At 原作者 @wentata

**Comment by wentata** [comment]
视乎饺子的大小吧，有些品牌的饺子较大，用勺子弯曲的表面不容易搬动饺子
铲子平面大，好控制

**Comment by wentata** [comment]
> 为啥要用铲子？勺子了解一下？

视乎饺子的大小吧，有些品牌的饺子较大，用勺子弯曲的表面不容易搬动饺子
铲子平面大，好控制

**Comment by Anduin2017** [comment]
Wont fix.
