### ISSUE TITLE
没有东西判断容积怎么办

### ISSUE THREAD

**Issue by nyancatda** [Anduin2017/HowToCook#25]
做饭要买烧杯和量筒吗

**Comment by LxnChan** [comment]
可以买一些容积固定的勺（比如料理盒的勺子一般是一勺1g）；液体的话可以买一些滴管，一般一管就是5ml左右

**Comment by HtwoO** [comment]
备一个厨房秤，水就称重直接按 1 毫升 1 克换算。

/me 确实有烧杯，不过对做菜来说不算实用

**Comment by nlp4whp** [comment]
多试几次就好了，至少比烧糊的碳好吃嘛🐶

**Comment by oceanxie** [comment]
大差不差就行

**Comment by TualatinX** [comment]
凭感觉，似乎分量差得不太多的话，味道一般都还可以的
