### ISSUE TITLE
调味料使用“勺”做单位要比“毫升”好掌握吧

### ISSUE THREAD

**Issue by goo1016** [Anduin2017/HowToCook#297]
毕竟不是谁家里都有能够准确测量几毫升的工具，而且每个人口味各异，每种调料多一点少一点也不是太大的问题，基本上有个一两次经验就可以基本掌握用量了。

**Comment by goo1016** [comment]
咱们这写出来是给人看的，又不是自动化脚本，几毫升的东西也不好量啊，放杯里量完再倒锅里估计就已经不够了😂

**Comment by futaojing** [comment]
用勺对新手来说特别劝退，因为有勺有大有小，你只需要知道你自己一勺是多少ml，对应多少ml用几勺就行

**Comment by awei-nan** [comment]
可以给出毫升与勺的对应关系，主要原因在于每家的勺大小也不尽相同，违背了本教程的宗旨

**Comment by wmswu** [comment]
我有个建议是否可行，勺子是否可以换成婴儿奶粉的勺子，这个勺子我就见过2种，一种是1平勺可以兑30ml水的 ,一种是一平勺兑60ml 水的，虽然勺子底部有孔但可以解决类似盐，孜然粉等固态粉装的调味料了 哈哈哈哈哈

**Comment by YanceyChan** [comment]
你看你家里勺子对应多少ml不就好了吗？还每次都用量杯？？

**Comment by CberYellowstone** [comment]
有国家标准勺好像，可以去淘宝买

**Comment by Anduin2017** [comment]
勺子的问题是有大有小。大的有一勺100ml的，小的有一勺2ml的。因此`勺`不是一个认可的单位。

`壶`，`把`  都不是认可的单位。
