### ISSUE TITLE
不建议在这里放太多菜谱

### ISSUE THREAD

**Issue by theBestVayne** [Anduin2017/HowToCook#301]
因为每个人的做法、口味、习惯不同，同一个菜会有超多不同版本的做法，它不属于普适性的知识。而烹饪原理是属于普适性的知识，比如您写的不粘锅的原理就很好，建议鼓励大家多贡献烹饪原理，原理会了就是一通百通。就像懂了计算机原理后，学其他编程语言都能很快上手。

**Comment by wmswu** [comment]
hello world 的demo 还是要有的，这些个菜谱可做为举一反三的一

**Comment by recolic** [comment]
此项目希望帮助对烹饪原理不感兴趣、或难以掌握的人，以形式化、机械化的步骤，完成一个可以接受的菜品，并填饱自己的肚子。

**Comment by OliverLew** [comment]
菜谱是死的，人是活的，口味不同可以灵活调整嘛。做饭这种事本来就需要模仿、学习、积累经验，丰富的菜谱可以给大家提供思路和灵感，是很有用的。

我开的一个issue里，[项目作者表明](https://github.com/Anduin2017/HowToCook/issues/293#issuecomment-1047651131)项目指向并不局限于程序员向，而可以面向任何人，菜谱很少的话，就不太友好了。

**Comment by Anduin2017** [comment]
引用：https://github.com/Anduin2017/HowToCook/issues/293#issuecomment-1047651131

这个仓库的价值观不是“面向程序员”，不是“面向新手”，而是“面向精准和量化”

确保这是唯一一个，任何人做菜，只要尊重菜谱，都能得到唯一结果的仓库。

这是它最重要的价值。我们希望保持这个价值。如果读者想得到灵活自由的菜谱，他可以去很多地方。但是如果他想得到一份清晰精准的菜谱，我希望这里是一个不错的答案。
