### ISSUE TITLE
【建议】能否做个分类，来对应不同人群，例如 孕妇(前期、中期、后期)适合吃的菜

### ISSUE THREAD

**Issue by mAndroidNovice** [Anduin2017/HowToCook#302]
如题

**Comment by Anduin2017** [comment]
是好想法。只是目前这个仓库是面向于如何做，而不是面向于营养搭配的

**Comment by LinMingQiang** [comment]
> 是好想法。只是目前这个仓库是面向于如何做，而不是面向于营养搭配的
仓库的发展速度可能超乎你的预期了，感觉还是需要做一个比较完善的分类结构，中国菜品没有上万也有成千，集中在readme的话太混乱了，readme可以加个分类链接。仓库目标可以从`如何做`转为`想做什么`的功能性项目。

**Comment by Anduin2017** [comment]
Duplicate #3
