### ISSUE TITLE
建议使用下厨房 APP

### ISSUE THREAD

**Issue by adoyle-h** [Anduin2017/HowToCook#33]
下厨房 APP 既有配图，又有定量的菜谱，又有流程。菜谱还很多。
不必重复造轮子。

**Comment by hcjcn** [comment]
这是程序员没有女朋友才建的项目，人艰不拆，人艰不拆，，不拆...

**Comment by Anduin2017** [comment]
这里主要是考虑，Git仓库相比商业运营的APP相比，有一些特点无法取代：

* 历史的永久保留
* 鼓励并支持社区贡献，并且能够随时追踪每一行的贡献人
* 协议开放且较弱
* 讨论方便

这会有助于未来构建更多有趣的事情。例如：基于这个Repo构建智能做饭机器人等。
