### ISSUE TITLE
【建议】关于文字排版

### ISSUE THREAD

**Issue by youthlin** [Anduin2017/HowToCook#36]
主要是看惯了有空格排版，看到没空格的段落会很不舒服……

参考：[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)

>「有研究显示，打字的时候不喜欢在中文和英文之间加空格的人，感情路都走得很辛苦，有七成的比例会在 34 岁的时候跟自己不爱的人结婚，而其余三成的人最后只能把遗产留给自己的猫。毕竟爱情跟书写都需要适时地留白。与大家共勉之。」
——[vinta/paranoid-auto-spacing](https://github.com/vinta/pangu.js)

- 中英文之间需要增加空格
- 中文与数字之间需要增加空格

（PS: 上述指南还有关于标点 、名词的约定也值得借鉴）

**Comment by Anduin2017** [comment]
PR welcome

**Comment by Anduin2017** [comment]
Fixed. Thanks!
