### ISSUE TITLE
好吃的泡面怎么煮？

### ISSUE THREAD

**Issue by jonZ92** [Anduin2017/HowToCook#406]

**Comment by Bersder** [comment]
参考[一包泡面十种吃法](https://www.bilibili.com/video/BV1s34y1X74a)

**Comment by StarGrin** [comment]
老铁在主食里  煮泡面加蛋

**Comment by aitianci** [comment]
先把喜欢的食材，比如蔬菜，鱼丸，蟹棒，土豆片等等等一切煮熟备用，起锅烧水下一包辛拉面，面煮到一半打个鸡蛋进去，然后等鸡蛋熟了就把煮好的食材扔进去，大火收汁到你能接受的辣度就好了。

**Comment by wangjiafenghw** [comment]
@金城武 这一秒的面和下一秒的面是不是两碗？

**Comment by Anduin2017** [comment]
主食里，有一道 炒方便面，是我本人亲自设计的。一定要尝一次呀

**Comment by Cogito2012** [comment]
建议把金城武的泡面做法加进去，参考：
[金城武的泡面](https://www.bilibili.com/video/BV1ot411b78T/)

**Comment by ChuKuang** [comment]
一根线椒切段备用 ，大蒜三瓣 切碎备用 ， 蘑菇撕成瓣备用  ，葱两根切碎备用。（）有条件的 猪后腿精肉切丝 先加食盐少许 生抽老抽少许搅拌腌制）  热锅加油少许 加大蒜 线椒段  炒出辣味，加蘑菇翻炒两下 加水煮 水开 下肉丝  打一个鸡蛋 ，等水开 下泡面 放泡面调料包（适量），泡面煮开  放葱，盛出即食

**Comment by free-jon** [comment]
> 主食里，有一道 炒方便面，是我本人亲自设计的。一定要尝一次呀

老铁，分享下制作步骤，

**Comment by Anduin2017** [comment]
> > 主食里，有一道 炒方便面，是我本人亲自设计的。一定要尝一次呀
> 
> 老铁，分享下制作步骤，

https://github.com/Anduin2017/HowToCook/blob/master/dishes/staple/%E7%82%92%E6%96%B9%E4%BE%BF%E9%9D%A2.md

**Comment by lizhikang16** [comment]
最好吃的做法是，先炒个西红柿鸡蛋卤，然后往卤里加水，再把泡沫放进去煮软即可，味道绝绝子
