### ISSUE TITLE
米饭工具除了电饭锅还有其他的工具吗

### ISSUE THREAD

**Issue by Edge2289** [Anduin2017/HowToCook#412]

**Comment by Hanoso** [comment]
汤锅也可以。
杭州过年疫情没回家，买了一袋米备着，第一次用汤锅蒸米饭时粘锅严重。后来百度了一下，在锅底抹点油，然后再蒸就可以了，锅底是一层焦黄的锅贴，可以铲的很干净。
后来我就改进了工序，参考如下:
1. 先炒菜，炒好后盛出来，但是不要刷锅；
2. 把淘好的米倒入锅中，水盖过米大概两指高；
3. 汤锅上横一双筷子，把盖子放在筷子上，目的是增加散气；
4. 电池炉用“蒸煮”功能，时间30分钟。
以上，到点就煮好了，也不会粘锅，锅底焦焦的一层锅巴，嘎嘣脆。炒菜也不用刷锅，省时间（又可以多大两把王者）。只需一个汤锅+电池炉即可，不用再买电饭煲，省出租屋的空间，搬家也方便。
🙃😛

**Comment by You-zeyi** [comment]
Dear niece or nephew, Uncle roger tell you, just buy a rice cooker, no need to deal with all the bullshit. If you cant afford a rice cooker, change your job.

**Comment by Edge2289** [comment]
> 亲爱的外甥外甥，罗杰叔叔告诉你，买个电饭煲就行了，不用管那么多废话。如果你买不起电饭煲，那就换工作吧。

ご回答ありがとうございました。箇人的には、ご飯を炊く道具をマスターするのはとても素晴らしいことだと思います。もちろん、炊飯器はご飯を炊く道具です。

**Comment by aitianci** [comment]
在做大量的米饭的时候，最常见的办法是不锈钢大盘+蒸锅蒸饭，能做到独立线程互相干扰小，效率高产量大能耗相对也不高。

**Comment by Huweicai** [comment]
I've tried cooking rice with microwave oven, emmm, however, it can work.....

**Comment by donglinz** [comment]
高压锅，有做米饭的程序

**Comment by Yakizzzz** [comment]
微波炉也可以   淘宝有卖微波炉焖饭的容器

**Comment by Anduin2017** [comment]
Close 因为已经有了其它方案。
