### ISSUE TITLE
没必要使用太过程序员的表达

### ISSUE THREAD

**Issue by royink** [Anduin2017/HowToCook#425]
一个「每人每份」就可以解决的表达方式，也不知道为什么非要用`Xg`*`人数`这种人类读起来费劲儿的表现手法。

**Comment by DreamVoid** [comment]
因为这是`程序员在家做饭方法指南。`

**Comment by ruin1990** [comment]
我觉得这很严谨啊，因为你不知道你以后会生几个娃，以后丈母娘和老丈人还有自己爹妈等其他亲戚会不会来吃饭是吧

**Comment by tydaytygx** [comment]
我觉得程序表达挺好 不然就跟普通的菜谱一样了

**Comment by XiaokunHou** [comment]
建议`xg`抽出来当做公共变量声明，方便维护。

**Comment by linlinger** [comment]
瞅瞅这repo名儿不就能解释一切了吗

**Comment by Anduin2017** [comment]
https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md
