### ISSUE TITLE
百毒不侵的食神

### ISSUE THREAD

**Issue by KINGLBT** [Anduin2017/HowToCook#428]
我朋友照着你的菜谱，一次做一周，做一次吃一周，我该如何教育他?@[chenqi199](https://github.com/chenqi199)

**Comment by chenqi199** [comment]
> 我朋友照着你的菜谱，一次做一周，做一次吃一周，我该如何教育他?

我的朋友就是我自己系列
你可以买个好点儿盒儿，走的时候体面点儿

**Comment by KINGLBT** [comment]
> > 我朋友照着你的菜谱，一次做一周，做一次吃一周，我该如何教育他?
> 
> 我的朋友就是我自己系列 你可以买个好点儿盒儿，走的时候体面点儿

做一次吃一周，一周闹了两次肚子，我该怎么让你改正

**Comment by Anduin2017** [comment]
Not an issue.
