### ISSUE TITLE
小炒黄牛肉炒5分钟吗？这样不就老了

### ISSUE THREAD

**Issue by kangkanglee** [Anduin2017/HowToCook#444]
按照自己的经验，小炒黄牛肉大火炒一分钟就可以了

**Comment by Anduin2017** [comment]
@IcedOtaku

icedotaku.dev@gmail.com

**Comment by IcedOtaku** [comment]
@kangkanglee 你说得对，感谢纠正😅

**Comment by IcedOtaku** [comment]
@Anduin2017 已在[fix: 小炒黄牛肉](https://github.com/Anduin2017/HowToCook/pull/478)中修复此问题
