### ISSUE TITLE
我们要不要加一些CI job去自动化一些步骤(自动更新README等)

### ISSUE THREAD

**Issue by keidarcy** [Anduin2017/HowToCook#474]
- 根据directory结构更新README。
- close长时间inactive的issue。

这个库越来越来大，手动更新太多人工操作了而且容易出现失误。
如果同意的的话，我可以写CI。

**Comment by dengxinlong** [comment]
支持

**Comment by Anduin2017** [comment]
可以。现在readme每天都有一大堆conflict。很多贡献者看起来根本不知道如何正确处理conflict。

**Comment by keidarcy** [comment]
好的呀。我有时间就着手开始。预计周末完成。
