### ISSUE TITLE
老铁，牛逼！！！

### ISSUE THREAD

**Issue by amazingchow** [Anduin2017/HowToCook#52]
能否设计一个执行程序，配置文件为每一步的材料和操作时间，然后操作时间一到闹钟（或其他东西）告知当前步骤要结束。。。粗略的想法。。。

**Comment by recolic** [comment]
这种想法或许等效于: 
设计一种形式化的机器语言, 用于描述一个菜谱的执行过程.

**Comment by recolic** [comment]
Move to #60

**Comment by amazingchow** [comment]
666
