### ISSUE TITLE
量貌似不要好掌握

### ISSUE THREAD

**Issue by Tyh2001** [Anduin2017/HowToCook#521]
每个菜多少g，佐料多少ml，我好像不太能掌握量🤔

**Comment by Bersder** [comment]
如果你倾向于经验派，你可以凭感觉来放，在多次实践中积累用量感觉，最后脱离工具。

如果你倾向于理论派，你可以准备咖啡电子称和不同规格的烧杯，在前面几次的料理中严格遵守用量，根据成品的味道动态调整用量，最终找到适合自己的最佳用量。

从经验派转到理论派是很难受的；但理论派转到经验派是比较容易的，或者也可以继续坚持经验派

**Comment by Tyh2001** [comment]
理论派是在是太机械了。。。。。

**Comment by FreedomLoading** [comment]
经验多了就好了,放调料可以少量多次用,然后尝咸淡,经验丰富了就基本上差不多了.
