### ISSUE TITLE
求出酸辣土豆丝教程

### ISSUE THREAD

**Issue by RRRoger** [Anduin2017/HowToCook#53]
个人感觉酸辣土豆丝很考验水平，有次亲戚做的酸辣土豆丝还有烧烤味 😄

**Comment by Funny-dot** [comment]
第一步：土豆洗净，切丝；
第二部：切好的土豆放入盆子中，盆子接入摸过土豆丝的水；沉淀5分钟，捞出，沥干；
第三部：依据个人爱好，准备配料，蒜苗，大蒜，青红辣椒，青椒要辣不辣看自己口味；
第四步：起锅，热锅，热锅放入冷油（这个依据土豆丝的多少来，自己看着放），等5秒；放入 人数 * 0.5g的盐巴；
第五步：翻炒油中的盐巴，油冒烟，快速的放入土豆丝；快速的翻炒；
第六步：土豆丝发软或者透明后放入 醋，适量辣椒粉，配料；
第七步：翻炒！最后放胡椒粉！
第八步：起锅，开饭！

**Comment by Anduin2017** [comment]
PR welcome!!

**Comment by RRRoger** [comment]
closed
