### ISSUE TITLE
咕噜肉需要 500 毫升油？

### ISSUE THREAD

**Issue by childe** [Anduin2017/HowToCook#576]
500 毫升是一整瓶农夫山泉吧？确定需要这么多油？

**Comment by childe** [comment]
[咕噜肉的做法](https://github.com/Anduin2017/HowToCook/blob/master/dishes/home-cooking/%E5%92%95%E5%99%9C%E8%82%89.md)

@wentata @Anduin2017

**Comment by wentata** [comment]
> 500 毫升是一整瓶农夫山泉吧？确定需要这么多油？

因为需要炸，我家的锅是用大概一小瓶
如果王刚的锅应该就要用12公升的油了
