### ISSUE TITLE
颜色描述标准化

### ISSUE THREAD

**Issue by recolic** [Anduin2017/HowToCook#58]
建议添加一个文档,对各种颜色的描述给定一个标准化的词汇. 
例如部分菜品中的颜色用于判断食材是否已达到某一阶段, 颜色描述与判定的标准化在标准化烹饪中较重要. (例如地三鲜中的金黄色)

实现方面, 可以直接采用一个已有的颜色命名体系(例如 https://www.w3schools.com/colors/colors_groups.asp ), 而采用给定命名体系之外的颜色名均是不允许的, 除非在某一个列表中手动添加颜色名-RGB value的对应表.

**Comment by Anduin2017** [comment]
好家伙……

不过我在想有没有什么方便取得的设备能够让做饭的人快速对菜品的颜色量化？

**Comment by Anduin2017** [comment]
有道理。只是感觉不好让贡献者（菜谱的作者）能够得到他的菜此时颜色的RGP

其实现在的一些描述，例如在做地三鲜时：“变成金黄色”

确实是个问题，考虑到不同人对于“金黄色”这个词的理解可能有偏差。在这种情况下我认为可以额外增加一些别的描述语，例如“一般需要至少15秒”来修正歧义。

**Comment by recolic** [comment]
贡献者也不一定要把颜色描述的非常准确。贡献者在使用颜色类词语时，只需看一眼色卡，保证自己的描述用词在色卡内能找到，并且`色卡中的那种颜色在这里就是可接受的`，就足够了。

这个颜色的描述"金黄色"，应该意味着`色卡里的'金黄色'就是一个很好的example,如果你不确定的话，它就是一个不错的例子`。
而不是`色卡里的‘金黄色‘一定是最适当的颜色`。

**Comment by recolic** [comment]
其实我们列出的这些菜谱本身，都不一定是最优的做法。番茄炒蛋估计就有十几种做法，我们的作者也不可能给出某一种做法的最优解。

我们的菜谱并非用于`真功夫`这类机器人控制的工业化中餐生产，我个人的观点认为，在家庭制作中，标准化(明确)和模糊化(不精确)是不冲突的。

**Comment by recolic** [comment]
关闭issue因为标准色卡的使用，对贡献者的要求过于严格。

**Comment by northword** [comment]
> 关闭issue因为标准色卡的使用，对贡献者的要求过于严格。

个人觉得这个还是可行的和有用的，因为对于颜色的认知主观性还是较强的。
我们可以将其作为可选项/建议项。规定一个色卡，将其作为建议，贡献者如果愿意，可以在色卡里找到合适的颜色描述，反之，则可以忽略这条。
有参考色卡的可以标注为形如 https://github.com/Anduin2017/HowToCook/issues/58#issuecomment-1044272917 中的描述： “ [色卡](https://github.com/Anduin2017/HowToCook/issues/58) 里的 [金黄色](https://www.w3schools.com/colors/color_tryit.asp?color=Yellow) 就是一个很好的 example ”。
