### ISSUE TITLE
图片似乎坏掉了

### ISSUE THREAD

**Issue by aimerneige** [Anduin2017/HowToCook#589]
![image](https://user-images.githubusercontent.com/51701792/156326894-7dee9bea-7fbe-482d-a590-742594189c83.png)

**Comment by Anduin2017** [comment]
https://cook.aiurs.co/dishes/drink/%E7%99%BE%E9%A6%99%E6%9E%9C%E6%A9%99%E5%AD%90%E7%89%B9%E8%B0%83/%E7%99%BE%E9%A6%99%E6%9E%9C%E6%A9%99%E5%AD%90%E7%89%B9%E8%B0%83/

Fixed.
