### ISSUE TITLE
红烧鲤鱼为啥需要五花肉？

### ISSUE THREAD

**Issue by sunbin1993** [Anduin2017/HowToCook#592]

**Comment by jerome-233** [comment]
1. 五花肉煸炒的时候会出猪油，相比较于植物油，动物油脂更香。
2. 煸炒至金黄的五花肉炖煮过后吃起来也很香的，相当于配菜。
3. 鱼类本身脂肪含量少，所以香味欠缺，着重的是肉质的口感。所以一般做鱼类菜都建议用猪油，想要一锅奶白香醇的鱼汤。猪油是最好的选择~

**Comment by shochikuR** [comment]
河鱼用五花肉去土腥味
