### ISSUE TITLE
建议项目移至gitee

### ISSUE THREAD

**Issue by zhangxuhong1024** [Anduin2017/HowToCook#603]
万一哪天海外的网络不好呢.(此处应有一个你懂的微笑).
传承千年的烹饪,千万中国码农的总结,总不能就这样白白送人了,是吧.

**Comment by LiuYzero** [comment]
日常pull一下吧 -_-
可以gitee备份，但不建议gitee做主仓库。
世界的才是世界的。

**Comment by LxnChan** [comment]
自己做一下gitee镜像不就行了

**Comment by Anduin2017** [comment]
https://gitee.com/Anduin2017/HowToCook
