### ISSUE TITLE
每日盐量5g上限与炒青菜矛盾

### ISSUE THREAD

**Issue by nygula** [Anduin2017/HowToCook#615]
辅料技巧中描述 :  一天的总盐量不建议超过 5g，参考[WHO](https://www.who.int/news-room/fact-sheets/detail/salt-reduction)
但是炒青菜中备料: 食盐 5g * 人数   ,这样的话是否人一天就只能吃一个青菜.别的啥都不能吃了?

**Comment by YukiRus** [comment]
青菜出水的，盐不会全部被你吃进去，有不少会溶解在水里，不要喝那个剩下的汤就行

**Comment by BUTUbird** [comment]
你总不能连汤都喝了吧

**Comment by Anduin2017** [comment]
参考社区的建议。别喝汤就行了。

**Comment by AsenHu** [comment]
这个 5 克盐，真的太多了，不管健不健康，真的很难吃下去，建议改 2 克。

![2024-11-12-21-10-56-979](https://github.com/user-attachments/assets/a81cacba-cb38-4df1-b714-ef0c4947cb2e)

![2024-11-12-21-33-12-935](https://github.com/user-attachments/assets/bb333544-8498-4573-8523-4b9aa816fac2)

那个纸上放的是盐，碗里是 70 毫升水，菜是 100 克的，你们看看是不是菜或者水少了，所以会这么咸
