### ISSUE TITLE
建议增加每日随机菜谱功能!

### ISSUE THREAD

**Issue by wizarot** [Anduin2017/HowToCook#621]
建议增加每日随机菜谱功能! 每天想吃什么实在太麻烦了.
最好还能自动出 配料单,方便回家路上一次买齐.哈哈哈!

**Comment by Vktun** [comment]
还得加个营养搭配，营养推荐

**Comment by LiuYzero** [comment]
甚至可以对接线上买菜平台是吧？
一键确认，送货到家。 🤔

**Comment by Anduin2017** [comment]
参考： https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md

这个功能不应该这个仓库做。而是应该由其它开发者将这份仓库 Fork 走，并额外开发。

这个仓库本来协议也是CC0的。而且格式都很严格，解析起来不难。

可以由任何感兴趣的人 fork 一下，再去做个Web服务或是APP什么的，可以往里加API来实现这种推荐算法。

这个仓库本身就不折腾这些了。它只保持一份精准、好解析的纯文本。
