### ISSUE TITLE
速冻水饺的方法严重错误

### ISSUE THREAD

**Issue by vvhh2002** [Anduin2017/HowToCook#629]
速冻水饺 应该使用温水或冷水下锅，不然会面都煮化了肉还没熟

**Comment by effycoco** [comment]
包装上都写的开水下锅啊

**Comment by Anduin2017** [comment]
https://www.zhihu.com/question/20822373

>水开后下锅


>最好不要冷水下锅，因为这样吃到的饺子要么烂，要么不安全，均不能反应该有风味(原因后面叙述)
