### ISSUE TITLE
小程序版本

### ISSUE THREAD

**Issue by LeeJim** [Anduin2017/HowToCook#634]
hi，我基于 HowToCook，做了一个小程序版本的程序员做饭指南。

想看看在 README 里可以加个露出吗？

https://github.com/LeeJim/HowToCookOnMiniprogram

**Comment by Anduin2017** [comment]
暂时不考虑引用派生库。派生库还是交给你自己运营吧。howtocook还是坚持作为底层基础设施，只提供菜谱。

不过，看起来这个小程序我好像没找到预览的入口…

**Comment by LeeJim** [comment]
README 有个小程序码，也可以微信上搜索“程序员做饭”

**Comment by Anduin2017** [comment]
Wow!!

我实际用了一次。非常优异的用户体验！居然还有计时功能！！

当然，换句话说，由于HowToCook还是定位成了基础库。我们其实希望看到有非常多的开发者，基于它开发出百花齐放的菜谱App。因此为了方便开发，我们甚至把它上架了npm。

看到你的优异的小程序，我真的十分开心。就像一个开发框架的维护者，看到了有人用这个框架制作出了非常优异的应用一样。

当然，HowToCook是Unlicense协议的。你可以自由使用这些内容创作。我非常鼓励和支持。

但是，考虑到我们不会一一审查所有引用者的CodeOfConduct是否和我们全部吻合，也为了避开商业运营的嫌，我们不会向任何上层App进行引流。考虑到我也非常喜爱你的小程序，我会尽可能在我的社交帐户上帮忙推广。但是不会改变这个仓库本来的意图：

> 提供一份足够精准的菜谱。

希望理解！

**Comment by Anduin2017** [comment]
当然，毕竟这是你自己的小程序，我也支持并且鼓励你往里额外扩展些你喜爱的东西，甚至添加广告来流量变现，或是向你的其它账号引流。我不会干预。请放心大胆的创新、拓展吧！

**Comment by LeeJim** [comment]
非常开心你喜欢这个小程序。
同时也理解你的出发点，虽然没能如常所愿，但还是非常感谢提供了这个有趣使用的项目。

**Comment by LeeJim** [comment]
非常开心你喜欢这个小程序。
同时也理解你的出发点，虽然没能如常所愿，但还是非常感谢提供了这个有趣使用的项目。

**Comment by Anduin2017** [comment]
@LeeJim  光阴似箭，时光荏苒。4年时光转瞬即逝。在这里，我想问问……

你的小程序还好吗？我扫了它，它看起来还能用，但是简直是考古数据（
