### ISSUE TITLE
《酿豆腐、酿苦瓜》

### ISSUE THREAD

**Issue by ashin98** [Anduin2017/HowToCook#666]
1.准备好豆腐、猪肉馅等食材
2. 猪肉馅中加入葱姜末、食盐、生抽、胡椒粉、料酒香油等调料搅拌至微微上劲备用。
3. 豆腐切成厚块。
4. 用小勺在表面掏一个洞，喜欢肉多可掏深些，但注意别掏破底。
5. 把腌好的肉馅填在豆腐洞里。
6. 平底锅放少许油，油热后用小火先将有肉馅的一面煎至微黄，
7. 一面煎黄后再翻过来煎另一面，几面都煎一下。

**Comment by Anduin2017** [comment]
Misplaced PR.
