### ISSUE TITLE
这第一道菜就标记多少克，难道我还需要买个称量一下吗 ？

### ISSUE THREAD

**Issue by birdyson** [Anduin2017/HowToCook#674]
[菠菜炒鸡蛋](https://cook.aiurs.co/dishes/vegetable_dish/%E8%8F%A0%E8%8F%9C%E7%82%92%E9%B8%A1%E8%9B%8B/%E8%8F%A0%E8%8F%9C%E7%82%92%E9%B8%A1%E8%9B%8B/#_2)
<img width="411" alt="image" src="https://user-images.githubusercontent.com/53157530/157577016-cb3bab63-0bc1-434b-966f-fa5f53f49952.png">

**Comment by ye-luo-xi-tui** [comment]
建议准备烧杯量筒移液枪

**Comment by pixel32** [comment]
哈哈哈哈哈😂

**Comment by Anduin2017** [comment]
#496
