### ISSUE TITLE
建议建仓出一个程序员买衣服指南

### ISSUE THREAD

**Issue by zlonqi** [Anduin2017/HowToCook#685]
例如，先拥有自己的身体数据：
![image](https://user-images.githubusercontent.com/29321205/157901473-40de5edf-cafa-474f-80a9-603e1362c9de.png)

**Comment by zlonqi** [comment]
然后网购的时候就能快速精准下单，杜绝退货带来的超大时间延迟。

**Comment by littlebearz** [comment]
然后搞团购？？？

**Comment by Anduin2017** [comment]
Off topic. Not an issue with this repo.
