### ISSUE TITLE
[建議]程式靈魂,竟然沒有提及臭蟲(bug)

### ISSUE THREAD

**Issue by freedy82** [Anduin2017/HowToCook#714]
如果您遵循本指南的制作流程而发现有问题或可以改进的流程，请提出 Issue 或 Pull request 。
建議應改為

如果您遵循本指南的制作流程而发现有臭虫或可以改进的流程，请提出 Issue 或 Pull request 。

另外建議把西紅柿炒雞蛋設成 Hello World 課程!

**Comment by xzhub** [comment]
影响食欲，不建议这样改。
