### ISSUE TITLE
地三鲜最后要放入的80g 淀粉,80g 是否是手误了?

### ISSUE THREAD

**Issue by mxm646690173** [Anduin2017/HowToCook#726]
地三鲜最后要放入的80g 淀粉,80g 是否是手误了,多打了个0?

**Comment by skyformat99** [comment]
你先放80g试试看效果如何

**Comment by mxm646690173** [comment]
> 你先放80g试试看效果如何

80g! 小半袋淀粉了,一袋淀粉才多少g

**Comment by Anduin2017** [comment]
计划降低成25g。我也觉得有点儿离谱。

**Comment by Anduin2017** [comment]
我自己没有亲自试，有条件的话，建议试验一下。如果不好吃，请reopen这个issue，并给出参考值，谢谢贡献！

**Comment by mxm646690173** [comment]
> 我自己没有亲自试，有条件的话，建议试验一下。如果不好吃，请reopen这个issue，并给出参考值，谢谢贡献！

晚上试了一下,感觉15g这个重量不太好把控, 因为做到最后,茄子没软, 大块的土豆内还是硬的,最好是给出合适大小的图片,淀粉的话, 试了一下, 大概控制在8g兑200ml的水的样子(一汤匙,个人感觉)
