### ISSUE TITLE
是【蚝油】不是【耗油】

### ISSUE THREAD

**Issue by Alvin18Leeee** [Anduin2017/HowToCook#730]
![image](https://user-images.githubusercontent.com/50413687/159451012-d1f32e75-1bca-4ad6-90cd-f4e422650127.png)

错别字重度强迫症表示坐立难安 = =

**Comment by Anduin2017** [comment]
不清楚，参考PR #717  ，作者 @WLHSDXN 

我当时搜了一下，确实有这道菜，而且就叫耗油生菜：

https://home.meishichina.com/recipe-223261.html

https://kknews.cc/zh-hk/food/2vlb2ay.html

https://m.meishij.net/html5/zuofa/haoyoushengcai_115.html

https://china-kitchen.lkk.com.cn/kitchen/zh-cn/recipe/0/1c/recipe-300/

**Comment by 5unnyWind** [comment]
> 不清楚，参考PR #717 ，作者 @WLHSDXN
> 
> 我当时搜了一下，确实有这道菜，而且就叫耗油生菜：
> 
> https://home.meishichina.com/recipe-223261.html
> 
> https://kknews.cc/zh-hk/food/2vlb2ay.html
> 
> https://m.meishij.net/html5/zuofa/haoyoushengcai_115.html
> 
> https://china-kitchen.lkk.com.cn/kitchen/zh-cn/recipe/0/1c/recipe-300/

这些文章也写错字了呗，材料都说了用蚝油了

**Comment by Anduin2017** [comment]
Thanks for contribution!

**Comment by wangdebiao** [comment]
耗（四声）油生菜是菜名，蚝（二声）油是调料，蚂蚁上树!=蚂蚁+树，同理耗油生菜!=耗油+生菜

**Comment by fagle** [comment]
油耗很高(⊙o⊙)…

**Comment by fagle** [comment]
> 油耗很高(⊙o⊙)…

**Comment by fagle** [comment]
> 耗（四声）油生菜是菜名，蚝（二声）油是调料，蚂蚁上树!=蚂蚁+树，同理耗油生菜!=耗油+生菜，非错别字，而是菜名如此，我猜测大概意思是这道菜比较耗油吧

油耗很高(⊙o⊙)…
