### ISSUE TITLE
快速推荐菜品功能

### ISSUE THREAD

**Issue by zundaren** [Anduin2017/HowToCook#750]
比如根据周一到周五，星期几，天气，性格，身体状况等快速搜索出符合条件的菜品推荐给用户

**Comment by Anduin2017** [comment]
参考： https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md

这个功能不应该这个仓库做。而是应该由其它开发者将这份仓库 Fork 走，并额外开发。
