### ISSUE TITLE
小火、中火、大火如何量化？

### ISSUE THREAD

**Issue by Grergo** [Anduin2017/HowToCook#752]
如题，不同设备，小火、中火、大火如何定义呢？

**Comment by Anduin2017** [comment]
大火：将燃气灶开到设计最大功率时的火焰。
中火：大火火焰体积的66%
小火：大火火焰体积的33%

**Comment by wangdebiao** [comment]
把手指伸进火焰中，0.3秒后快速抽回
小火：手指感到温暖
中火：手指感到热，有一点胀痛的感觉
大火：烫，有明显疼痛感

**Comment by LanFly** [comment]
准确的说，煤气灶应该用热功率来衡量，一般的煤气灶都会标明热功率，目前家用普遍最大是52kw，当然，还要考虑到锅的材质以及厚度，热传导效率，热蒸发效率等。

建议用一台典型的煤气灶为参考，分别用旋钮的 1/3、2/3、3/3 表示小火、中火、大火。

**Comment by Cathgao** [comment]
煤气灶上面不是都有标识吗，就按那个

**Comment by EvanHsieh0415** [comment]
> 煤气灶上面不是都有标识吗，就按那个

有些的沒有中火，大火是中間，小火是轉到底

**Comment by pcform** [comment]
> 准确的说，煤气灶应该用热功率来衡量，一般的煤气灶都会标明热功率，目前家用普遍最大是52kw，当然，还要考虑到锅的材质以及厚度，热传导效率，热蒸发效率等。
> 
> 建议用一台典型的煤气灶为参考，分别用旋钮的 1/3、2/3、3/3 表示小火、中火、大火。

5.2kw
