### ISSUE TITLE
请引入 husky  lint-staged 等做代码检查，校验pr 自动校验失败，反复提交修改！

### ISSUE THREAD

**Issue by yangnuowei88** [Anduin2017/HowToCook#755]
当前代码提交与集成校验不同步，导致提交PR后总失败，匹配起来！

**Comment by Anduin2017** [comment]
Close 因为不知道在说什么……

**Comment by Anduin2017** [comment]
我个人是用了vscode里的markdownlint插件，基本上各种小问题都能发现。

不过你说的有道理。只是我感觉，哪怕把策略改成了任何分支、任何仓库的任何提交都进行验证，可能其它开发者也不会注意到这件事……

另外我确实很想把ruby干掉。。现在开发这个玩意儿需要的依赖项太多了

**Comment by Anduin2017** [comment]
现在直接在 PR 时，检查提交的内容是否符合markdown格式要求，是实现起来比较容易的了。基本上大家意识到自己PR被打了个大红叉，都去点开这个红叉下面的错误信息看看为什么，然后再回来修。

如果是以前贡献过好多次的贡献者，基本上都知道这个语法大概是什么要求，效率还算可以。主要是很多人第一次来，不知道这个仓库是有检查要求的，也不太会用GitHub的这种，现在的情况就是我一般只看打了绿勾的PR

**Comment by yangnuowei88** [comment]
你说的也没错，但你看看，第一次项目上提pr,能一次性过过的能有几个？这个通过率你可以观察，所以说，在提交代码前做检查是很有必要的！

**Comment by yangnuowei88** [comment]
**现在的痛点是为啥PR通过率那么低，毕竟我们的东西内容为王，就因为格式，术语等，导致优质的内容丢失，这...**
