### ISSUE TITLE
直接做成一个计算器？

### ISSUE THREAD

**Issue by madisontanle** [Anduin2017/HowToCook#762]
![image](https://user-images.githubusercontent.com/46909580/160085268-e297e651-9e1f-4418-9231-cbc422101c52.png)

**Comment by madisontanle** [comment]
还得可视化强一点

**Comment by Anduin2017** [comment]
根据行为准则： https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md

这项工作不应该在这个仓库中完成。请fork后自行修改、开发、运营。
