### ISSUE TITLE
自己简单写了一个菜谱转 JSON

### ISSUE THREAD

**Issue by samzhangjy** [Anduin2017/HowToCook#766]
大大们好，我无意间看到了这个项目，感觉很有用，于是就写了一个 Markdown 文档的菜谱转换到 JSON 文件到简易转换器。

目前做到了“计算”中各食材用量的检测和简易的步骤说明，还不算太完善，等有时间可能会完善一下。

项目地址：https://github.com/samzhangjy/CookEverything

希望 HowToCook 能越来越好！

**Comment by Anduin2017** [comment]
Cool!

**Comment by Anduin2017** [comment]
什么时候能做到 JSON 转菜谱，这个仓库就在形式化的道路上一去不复返了

**Comment by Anduin2017** [comment]
Close because not an issue.
