### ISSUE TITLE
油温几成热需要量化或者检验方法

### ISSUE THREAD

**Issue by JustgoFlyme** [Anduin2017/HowToCook#778]

**Comment by allinu** [comment]
这里又一个相关链接 https://www.sohu.com/a/392288068_356444

**Comment by JiYouMCC** [comment]
最精准的是买个油温枪，有的菜谱比较精准，比如130°油炸，200°油炸就可以了

**Comment by Anduin2017** [comment]
Fixed already.

https://cook.aiurs.co/tips/advanced/%E6%B2%B9%E6%B8%A9%E5%88%A4%E6%96%AD%E6%8A%80%E5%B7%A7/
