### ISSUE TITLE
关于通用腌制中的料酒

### ISSUE THREAD

**Issue by Alcanderian** [Anduin2017/HowToCook#791]
料酒的基本作用是达到去腥和增香的作用，但是很容易让人忽略的的一点是，料酒本身的味道很浓，很容易掩盖食材本身的香味，对于腥味不浓郁的食材不适宜用料酒。尤其是牛肉和鱼肉，鸡肉。

- 对于鸡肉，可以用白酒去代替料酒。
- 对于牛肉，用姜葱水代替料酒，而不是写一个慎用就算了。
- 对于白色鱼肉，只需要清洗干净血丝和粘膜就不会有什么腥味了，不加酒。
- 对于红色鱼肉，个人经验不多，但是也不建议用料酒。

**Comment by Anduin2017** [comment]
https://github.com/Anduin2017/HowToCook/commit/6382f09d05c3eb14795424bb7d819367d9a92d7f

**Comment by tatwd** [comment]
建议使用黄酒代替料酒
