### ISSUE TITLE
红烧冬瓜的切块大小描述模糊

### ISSUE THREAD

**Issue by peacemo** [Anduin2017/HowToCook#815]
如题

dishes/vegetable_dish/红烧冬瓜/红烧冬瓜.md

操作一栏下第一条关于“切小块”的描述能否更精确些，厨盲表示切大了会不会不入味。

**Comment by wangdebiao** [comment]
是呢，我写的菜谱的小块都标注了1cm³，多一丝少一毫都不行

**Comment by peacemo** [comment]
我是真的不知道小块具体多大，那个碗旁边也没啥参照物。所以我就提交个issue问看看能不能具体一些，不至于回得这么阴阳怪气🙏，不行就吧issue关了。> 是呢，我写的菜谱的小块都标注了1cm³，多一丝少一毫都不行

**Comment by wangdebiao** [comment]
没有呀，请查看陕北熬豆角的做法，我在里面写的就是1cm³小块，我在阐述一个事实，并没有语气

**Comment by wangdebiao** [comment]
切的大了小了不知道做好是什么样子的，所以我写了多一丝少一毫都不行，不然做的不好吃还说我菜谱不行

**Comment by peacemo** [comment]
> 没有呀，请查看陕北熬豆角的做法，我在里面写的就是1cm³小块，我在阐述一个事实，并没有语气

原来是这样，我还以为你说我要求太多了嘞🤣误会

**Comment by Anduin2017** [comment]
Close
