### ISSUE TITLE
葱煎豆腐全程没有用到葱

### ISSUE THREAD

**Issue by monkeylord** [Anduin2017/HowToCook#83]
[葱煎豆腐](https://github.com/Anduin2017/HowToCook/blob/master/%E8%91%B1%E7%85%8E%E8%B1%86%E8%85%90.md)

Warning：定义了葱花，但是从未使用。

**Comment by longwusha** [comment]
好有道理，备用，然后没然后了。。。

**Comment by AlliotTech** [comment]
依个人口味装盘后调用😂

**Comment by recolic** [comment]
或许我们需要编辑一下原菜谱

**Comment by Anduin2017** [comment]
我直接assign给原作者吧……因为我也不会做这道菜……

**Comment by AlliotTech** [comment]
😂周末不加班  摸鱼的时候来更

**Comment by hax** [comment]
需要 linter！

**Comment by hax** [comment]
楼主的link失效了，现在是 https://github.com/Anduin2017/HowToCook/blob/master/dishes/home-cooking/%E8%91%B1%E7%85%8E%E8%B1%86%E8%85%90.md
