### ISSUE TITLE
[feature request] 增加自动比价并买菜脚本

### ISSUE THREAD

**Issue by xujuntwt95329** [Anduin2017/HowToCook#836]
可以实现一个脚本自动调用各个平台的接口，计算出最省的购买方式并生成订单

**Comment by Anduin2017** [comment]
根据行为准则： https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md

这项工作不应该在这个仓库中完成。请fork后自行修改、开发、运营。
