### ISSUE TITLE
我不会用GITHUB提交... 提交了5次了都被自动拒绝...

### ISSUE THREAD

**Issue by nuomiaa** [Anduin2017/HowToCook#892]
https://github.com/Anduin2017/HowToCook/pull/891
好累...

**Comment by Anduin2017** [comment]
请阅读ci的输出

**Comment by e5u** [comment]
文件 /home/runner/work/HowToCook/HowToCook/dishes/semi-finished/底料/牛油火锅底料(重庆)/牛油火锅底料(重庆).md 不符合仓库的规范！勺 不是一个精准的单位！

文件 /home/runner/work/HowToCook/HowToCook/dishes/semi-finished/底料/牛油火锅底料(重庆)/牛油火锅底料(重庆).md 不符合仓库的规范！ 它没有包含必需的附加内容！

**Comment by qhy040404** [comment]
Close #892
