### ISSUE TITLE
处理pr的小建议

### ISSUE THREAD

**Issue by qhy040404** [Anduin2017/HowToCook#912]
@Anduin2017 在处理包含多个commit的pr时，用squash and merge会使repo的commit记录更加整洁
直接merge可能会一次性多好几个commit，squash后就整合成一个
如图
![](https://raw.githubusercontent.com/qhy040404/issue-photos/master/merge-and-squash.png)

**Comment by qhy040404** [comment]
@Anduin2017

**Comment by Anduin2017** [comment]
好主意。
