### ISSUE TITLE
 【厨房准备】可以再添加一个【厨房秤】用来精准测量用量

### ISSUE THREAD

**Issue by minisailboat** [Anduin2017/HowToCook#923]

**Comment by HeZean** [comment]
https://github.com/Anduin2017/HowToCook/blob/1cc6294b44996753df3520c8ea1ca7c143f4b8e8/tips/%E5%8E%A8%E6%88%BF%E5%87%86%E5%A4%87.md?plain=1#L28

这里已经提及了，`电子秤` 应与常见 `厨房（电子）秤` 同义
