### ISSUE TITLE
炸薯条中预热空气炸锅的目的不明确

### ISSUE THREAD

**Issue by MoYuM** [Anduin2017/HowToCook#945]
炸薯条的菜谱中，预热空气炸锅的目的是什么？

**Comment by Anduin2017** [comment]
At 原作者 @AuroraTea

**Comment by AuroraTea** [comment]
> 炸薯条的菜谱中，预热空气炸锅的目的是什么？

放入食材的时候锅内温度已经处于烹饪所需温度。就好像油炸薯条要等油热而不是直接往油里放薯条。
