### ISSUE TITLE
有点好奇为什么大家要纠结调料和配料的用量问题

### ISSUE THREAD

**Issue by ID-VerNe** [Anduin2017/HowToCook#980]
很多时候适量就很能说明问题了，按照个人口味想给多少就给多少，这次不够下次加，这次多了下次减就好。

**Comment by OregonBanner** [comment]
个人认为[这个文档中的CODE_OF_CONDUCT.md](https://github.com/Anduin2017/HowToCook/blob/master/CODE_OF_CONDUCT.md)可以足够说明您所提问的问题了

**Comment by ID-VerNe** [comment]
怪不得怪不得
