### ISSUE TITLE
提交pr报的是master自带一个文件长度超长了./CODE_OF_CONDUCT.md，导致pr一直被拒绝

### ISSUE THREAD

**Issue by yizhihuamao** [Anduin2017/HowToCook#989]
Run mdl . -r ~MD036,~MD024,~MD004,~MD029
./CODE_OF_CONDUCT.md:51: MD013 Line length

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
Error: Process completed with exit code 1.

这是手册不应该限制长度，很多文本需要较长介绍

**Comment by woojufon** [comment]
不更改将永远无法提交pr

**Comment by Anduin2017** [comment]
抱歉造成不便。已经修正。十分感谢提醒！
